### ISSUE TITLE
Protect the code that assigns component default values

### ISSUE THREAD

**Issue by bancika** [bancika/diy-layout-creator#431]
in cases like open jack failure, so it doesn't fail catastrophically.

**Comment by bancika** [comment]
java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.diylc.common.PropertyWrapper.writeTo(Unknown Source)
	at org.diylc.presenter.InstantiationManager.fillWithDefaultProperties(Unknown Source)
