### ISSUE TITLE
First time install of 3.53 does not create .diylc folder and config.xml and logs folder not created

### ISSUE THREAD

**Issue by PH0MB** [bancika/diy-layout-creator#436]
Subject says it all. I used a 3.52 zip version (not installer) and runned that one. That creates the .diylc folder and the config.xml, but no logs folder. I created the logs folder manualy and all works normal.
running on Win7 32bit laptop and java 8 v201. so upgrading from older version works, but not on  first install.
00:36:24,781 DEBUG [main] DIYLCStarter - Java version: 1.8.0_201-b09 by Oracle Corporation
00:36:24,781 DEBUG [main] DIYLCStarter - OS: Windows 7 6.1
00:36:24,781  INFO [main] DIYLCStarter - Starting DIYLC with working directory C:\Program Files\DIYLC
00:36:24,921 DEBUG [Thread-2] DIYLCStarter - Starting font pre-loading
00:36:24,921  INFO [Thread-2] DIYLCStarter - Dynamically loading font: consola.ttf
00:36:25,451  INFO [Thread-2] DIYLCStarter - Dynamically loading font: lucon.ttf
00:36:25,451  INFO [Thread-2] DIYLCStarter - Dynamically loading font: square721_bt.ttf
00:36:25,748 DEBUG [Thread-2] DIYLCStarter - Finished font pre-loading
00:36:26,200  INFO [main] ConfigurationManager - Initializing configuration
00:36:26,200 ERROR [main] ConfigurationManager - Could not initialize configuration
java.io.FileNotFoundException: config.xml (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at org.diylc.appframework.miscutils.ConfigurationManager.initializeConfiguration(ConfigurationManager.java:86)
	at org.diylc.appframework.miscutils.ConfigurationManager.<init>(ConfigurationManager.java:59)
	at org.diylc.appframework.miscutils.ConfigurationManager.getInstance(ConfigurationManager.java:50)
	at org.diylc.swing.gui.DialogFactory.initialize(Unknown Source)
	at org.diylc.swing.gui.MainFrame.<init>(Unknown Source)
	at org.diylc.DIYLCStarter.main(Unknown Source)

**Comment by bancika** [comment]
fixed for 3.54
